### ISSUE TITLE
Snake Main Menu

### ISSUE THREAD

**Issue by Queng123** [Miou-zora/B-OOP-400-NAN-4-1-arcade-alexandre.franquet-mirror#12]
# Details
Create main menu for snake game, with 2 buttons : 
- Start
- Quit

# Tasks

- [x] : create main game menu interface when game is lunch
- [x] : create button start that change game state to "GAME"
- [ ] : create button quit that go back to MAIN PROGRAM MENU
