### ISSUE TITLE
Snake Pause Menu

### ISSUE THREAD

**Issue by Queng123** [Miou-zora/B-OOP-400-NAN-4-1-arcade-alexandre.franquet-mirror#13]
# Details
Create pause menu for snake game, with 3 buttons : 
- Resume
- Restart
- Quit

# Tasks

- [ ] : create pause menu interface when key **escape** pressed
- [ ] : navigate in menu with **arrows** and select with **space**
- [ ] : create button resume that continue the game
- [ ] : create button restart that restart the game
- [ ] : create button quit that go back to MAIN GAME MENU
