### ISSUE TITLE
Game End Menu

### ISSUE THREAD

**Issue by Queng123** [Miou-zora/B-OOP-400-NAN-4-1-arcade-alexandre.franquet-mirror#14]
# Details
Create game end menu that display score and can restart game. It also display quit section.

# Tasks
- [ ] : create game end interface with score to display
- [ ] : change button with **ARROWS** and select with **SPACE**
- [ ] : display restart button that restart game
- [ ] : display quit button that go back to the game menu
