### ISSUE TITLE
library loader

### ISSUE THREAD

**Issue by Queng123** [Miou-zora/B-OOP-400-NAN-4-1-arcade-alexandre.franquet-mirror#21]
# Details
Create function that get every ".so" files, and stock them in 2 catégories: 
- games
- graphical libs

# Tasks
- [ ] : search for "./lib" folder
- [ ] : get every ".so" files
- [ ] : stor them in 2 catégories
